### ISSUE TITLE
The mod doesn't work if you have changed the sprint keybind

### ISSUE THREAD

**Issue by SmajloSlovakian** [whimsicalities/DontUntoggleSprint#1]
the mod just doesn't work... if i die and have my sprint toggled on, the sprint toggles off...
i tried it without any additional mods on 1.20.1

**Comment by SmajloSlovakian** [comment]
update: the mod doesn't work if you have sprint keybind changed

it probably has something to do with this line:
KeyMapping.set(client.options.keySprint.getDefaultKey(), true);
where the getDefaultKey() method gets the default key and presses that instead of the key that's set by the player (if it is changed by the player)

**Comment by SmajloSlovakian** [comment]
i fixed it and made a pull request

**Comment by whimsicalities** [comment]
Hi, thanks for the report! I'm not able to fix this or review the PR at the moment, but I'll take a look as soon as I am able to.

**Comment by whimsicalities** [comment]
Fixed in 1.2.0
